[SDK-164] Add account creation popup
readyplayerme/rpm-unity-sdk-avatar-creator pull request #23
Opened 2023-05-22 15:26 UTC by rYuuk

## [SDK-164](https://ready-player-me.atlassian.net/browse/SDK-164)

## Description

- Account creation popup appears when user is not signed and and next button is clicked on creating an avatar

## Changes

#### Added

- Signup endpoint and API
- Account creation popup
- UI elements to prefab

## How to Test

- Create an avatar without signing in and click on next button
- Try entering new email and clicking on continue without signup and close button

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.
-   [ ] QA Testing is updated.

## QA Testing

-   Mention any useful test cases for this feature and add to QA Testing documentation.

## Details

-   If more details are necessary to support the description with images and videos add them here.

2023-05-23 10:28 UTC, srcnalt commented on Samples~/Scripts/Utils/ValidatorUtil.cs
> +        private const string EMAIL_REGEX = @"^[\w!#$%&'*+\-/=?\^_`{|}~]+(\.[\w!#$%&'*+\-/=?\^_`{|}~]+)*"
We can be less strict about emails, I remember the most basic rule is `*@*` which can be a valid email. We had issues due to use of strict regex before with avatar urls.

2023-05-23 10:30 UTC, srcnalt commented
I think close button on RPM website also acts as continue without email button. So we can let user go to at that point to.
Also we can probably use dark theme for email popup since I'd fit current color schema we provide.

2023-05-23 10:49 UTC, HarrisonHough commented on Samples~/Scripts/Utils/ValidatorUtil.cs
> +        private const string EMAIL_REGEX = @"^[\w!#$%&'*+\-/=?\^_`{|}~]+(\.[\w!#$%&'*+\-/=?\^_`{|}~]+)*"
+1 to sarges comment. 
While it is nice to enforce strict email format, it may have some strange edge cases. We can leave it as a very simple regex and then developers can add their own more complicated validation if they want.

2023-05-23 10:55 UTC, HarrisonHough requested changes
The hard coded strings aren't a blocker for me but I think the strict regex should be adjusted to something like sarges suggestion.

2023-05-23 10:55 UTC, HarrisonHough commented on Runtime/WebRequests/AuthenticationRequests.cs
> +            var payload = new JObject(new JProperty("data",
This "data" string is hardcoded in multiple places, if we ever needed to update it would be annoying to change. Would be better to put it in a constant I think. 
The same could be said for "email" and "token" potentially.

2023-05-25 05:52 UTC, HarrisonHough approved these changes
Looks good now. Cool stuff

2023-05-25 08:32 UTC, merged