feat: move all endpoints to one class
readyplayerme/rpm-unity-sdk-avatar-creator pull request #49
Opened 2023-09-14 14:45 UTC by rYuuk

## [TICKETID](https://ready-player-me.atlassian.net/browse/TICKETID)

## Description

-   Briefly describe what this change will do

## How to Test

-   Add steps to locally test these changes

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.

2023-09-14 15:03 UTC, MaxAndreassenRPM commented on Runtime/Data/Endpoints.cs
> +namespace ReadyPlayerMe.AvatarCreator
This is an interesting approach, what has brought on this move to having a large endpoint file with a load of methods in it to return endpoint urls? 🤔

2023-09-14 15:49 UTC, MaxAndreassenRPM commented on Runtime/Data/Endpoints.cs
> +namespace ReadyPlayerMe.AvatarCreator
Ah okay cool, makes total sense. IMO this is better, but still not perfect as having one big 'endpoints' file that forever grows as the SDK needs to use more endpoints isn't ideal. Instead my preference would be the approached I outlined in that thread. However, this is still an improvement on the previous version! 👍

2023-09-14 18:28 UTC, rYuuk commented
@MaxAndreassenRPM I have separated out different classes for different types of endpoints. Also added a base class for base url. I am not sure whether naming of classes and functions are great, but let me know if you have suggestions regarding them.

2023-09-18 06:40 UTC, HarrisonHough requested changes
Overall code looks good. But just an issue right now that you can't load the final avatar due to this failure to pass metadata.

2023-09-18 06:40 UTC, HarrisonHough commented on Runtime/Data/Endpoints/AvatarEndpoints.cs
> +            return $"{AVATAR_API_V2_ENDPOINT}/{avatarId}.json";
When I was testing, this was failing because v2 endpoint has extra fields in the metadata/json that it seems our SDK doesn't know how to handle 
![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/assets/7085672/3ba59257-8e5b-4d6b-89b2-788770b8b9a8)
![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/assets/7085672/c07a32f5-7fee-4412-a46f-dfdb30baf169)

2023-09-18 09:41 UTC, HarrisonHough approved these changes
Yep all good now!
Cool stuff

2023-09-18 10:12 UTC, merged