feat: refactor category button and panels
readyplayerme/rpm-unity-sdk-avatar-creator pull request #51
Opened 2023-09-19 08:41 UTC by rYuuk

## [TICKETID](https://ready-player-me.atlassian.net/browse/TICKETID)

## Description

-   Briefly describe what this change will do

## How to Test

-   Add steps to locally test these changes

## Checklist

-   [ ] Tests written or updated for the changes.
-   [ ] Documentation is updated.
-   [ ] Changelog is updated.

2023-09-20 07:08 UTC, HarrisonHough requested changes
Some minor things in the comments. 
However the blocker is that there seems to be an issue in the "selected" logic in some of the categories. 
For example I was testing and ended up with 2 selected icons 
![image](https://github.com/readyplayerme/rpm-unity-sdk-avatar-creator/assets/7085672/6e4c0938-fed2-495e-b621-3819aaf0aea1)

2023-09-20 07:08 UTC, HarrisonHough commented on Samples~/Scripts/UI/CategoryUICreator.cs
> +            SelectYo(Category.FaceShape);
what does the "Yo" in SelectYo stand for here?

2023-09-20 07:08 UTC, HarrisonHough commented on Samples~/Scripts/UI/PanelSwitcher.cs
> +                    OutfitCategoryPanel.SetActive(false);
kind of a random idea but would it be simpler (at least in terms of maintenance and perhaps readability) to set all panels to false before the switch statement, and then only activate the panels needed? 🤔 
It would make it harder to "forget" to disable 1 panel. 
Just an idea though, not a blocker :D

2023-09-20 07:17 UTC, HarrisonHough commented
> Some minor things in the comments. However the blocker is that there seems to be an issue in the "selected" logic in some of the categories. For example I was testing and ended up with 2 selected icons ![image](https://user-images.githubusercontent.com/7085672/269192620-6e4c0938-fed2-495e-b621-3819aaf0aea1.png)
> 
> The issue seems to happen if you select an outfit subcategory the first time (by default none is selected) then you select another option, it highlights the new option, but doesn't unhighlight the "none" option. If however you click the "none" then select another it seems to fix itself.

Actually now I think of it, having the "none" category for outfits makes the UX a bit tricky and confusing. 
I had to say it but I would suggest replicating how it is in web. 
Basically it has no "none" option. Its just if you select a fullbody outfit, it will switch to that, if you select any module asset, it will load the every with the selected, plus a default or any previously selected asset from the other modular assets. 

EG 
1. select top 2
2. Avatar loads with top 2 and default bottom 1, shoes 1
3. select fullbody outfit - load fullbody outfit (no more modular assets)
4. select bottom 4
5. avatar loads with bottom 4, top 2 and shoes 1

2023-09-20 08:47 UTC, rYuuk commented on Samples~/Scripts/UI/CategoryUICreator.cs
> +            SelectYo(Category.FaceShape);
oh I forgot to rename it 😅

2023-09-20 08:48 UTC, rYuuk commented on Samples~/Scripts/UI/PanelSwitcher.cs
> +                    OutfitCategoryPanel.SetActive(false);
That's a good idea 💯 
Will do it.

2023-09-20 08:49 UTC, rYuuk commented
> > Some minor things in the comments. However the blocker is that there seems to be an issue in the "selected" logic in some of the categories. For example I was testing and ended up with 2 selected icons ![image](https://user-images.githubusercontent.com/7085672/269192620-6e4c0938-fed2-495e-b621-3819aaf0aea1.png)
> > The issue seems to happen if you select an outfit subcategory the first time (by default none is selected) then you select another option, it highlights the new option, but doesn't unhighlight the "none" option. If however you click the "none" then select another it seems to fix itself.
> 
> Actually now I think of it, having the "none" category for outfits makes the UX a bit tricky and confusing. I would suggest replicating how it is in web (yes I know we don't always want to be replicating web creator but I think in this case it is better). Basically it has no "none" option. Its just if you select a fullbody outfit, it will switch to that, if you select any module asset, it will load the every with the selected, plus a default or any previously selected asset from the other modular assets.
> 
> EG
> 
> 1. select top 2
> 2. Avatar loads with top 2 and default bottom 1, shoes 1
> 3. select fullbody outfit - load fullbody outfit (no more modular assets)
> 4. select bottom 4
> 5. avatar loads with bottom 4, top 2 and shoes 1

Forgot to see that there was no none category for modular assets. Will remove the clear button.

2023-09-21 05:35 UTC, HarrisonHough requested changes
I couldn't spot any issues in the code but when testing it seems that there might be a new bug. 
Not sure if our end our on backend. 
I will share a video in slack but to get the bug I did the following. 
1. selected a top (fullbody avatar)
2. selected selected a bottom 
3. selected a fullbody outfit
4. selected a top (modular) asset again, this it where it broke, the avatar didn't update again it was stuck with the outfit from step 3 for some reason

2023-09-21 13:21 UTC, HarrisonHough approved these changes
Code looks good and seems to be working now. Just some minor things in the comments, I think you accidently left some debug logs in there.

2023-09-21 13:21 UTC, HarrisonHough commented on Samples~/Scripts/UI/AssetButtonCreator.cs
> +            Debug.Log("Called: CreateAssetButtons: " + category);
and this?

2023-09-21 14:05 UTC, merged